name: 构建镜像

on:
  workflow_dispatch:
  # 只保留手动构建
  # 如果不想这个年更项目一更新就原地去世，请保持注释
  # push:
  #   branches:
  #     - master

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: tieba-cloud-sign

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建镜像
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Get version
        run: |
          version=$(sed -n "s/define('SYSTEM_VER', '\([^']*\)');/\1/p" init.php)
          echo "version=${version}" >> "$GITHUB_ENV"

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - 
        name: Set Up Cache
        uses: actions/cache@v4
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx

      - 
        name: Buildx
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm,linux/s390x
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.version }}
